/**
 * Module C — SVG parsing engine.
 *
 * Parses an exported figure into SciCompose's model:
 *  - assigns stable data-scid to every drawable element
 *  - measures real geometry (bbox/length) by briefly rendering offscreen
 *  - C2 detects text-converted-to-paths
 *  - C3 aggregates data elements into series (by group / color / collection)
 *  - C4 records fill + gradient references so recoloring can reach them
 *  - runs role recognition (Module D1) and writes data-scrole / data-scseries
 *
 * The returned `svg` string carries all data-sc* attributes and is the panel's
 * source of truth from then on.
 */
import type {
  BBox,
  DataSeries,
  ElementRole,
  ImportWarning,
  PanelMode,
  ParsedElement
} from "../types";
import { DATA_ROLES } from "../types";
import { classifyColor, parseColor, toHex } from "./colorUtils";
import { getStyleNumber, getStyleValue } from "./styleAccessor";
import { assignRoles } from "./roles";

const SVGNS = "http://www.w3.org/2000/svg";
const DRAWABLE = new Set(["path", "polyline", "polygon", "line", "rect", "circle", "ellipse", "text", "image", "use"]);
const SKIP_ANCESTORS = new Set(["defs", "clippath", "marker", "symbol", "mask", "pattern"]);

export interface ParseResult {
  svg: string;
  vb: BBox;
  elements: ParsedElement[];
  series: DataSeries[];
  textToPath: boolean;
  mode: PanelMode;
  warnings: ImportWarning[];
}

let scidCounter = 0;
function nextScid(): string {
  scidCounter += 1;
  return `sc${scidCounter.toString(36)}`;
}

/** Small stable hash of a string -> short base36 token (for series ids). */
function hashKey(s: string): string {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(36);
}

/** True if any ancestor is a non-rendering container (defs/marker/etc). */
function inSkippedAncestor(el: Element): boolean {
  let p = el.parentElement;
  while (p) {
    if (SKIP_ANCESTORS.has(p.tagName.toLowerCase())) return true;
    p = p.parentElement;
  }
  return false;
}

/** Concatenate id/class of the element and its ancestors as a recognition hint. */
function idHintOf(el: Element): string {
  const parts: string[] = [];
  let p: Element | null = el;
  let depth = 0;
  while (p && depth < 6) {
    const id = p.getAttribute("id");
    const cls = p.getAttribute("class");
    if (id) parts.push(id);
    if (cls) parts.push(cls);
    p = p.parentElement;
    depth += 1;
  }
  return parts.join(" ").toLowerCase();
}

function resolveGradientId(fill: string | null): string | null {
  if (!fill) return null;
  const m = fill.match(/url\(["']?#([^)"']+)["']?\)/);
  return m ? m[1] : null;
}

// ---------------------------------------------------------------------------
// Origin (OriginLab) support.
//
// Real Origin exports break the generic recognizer in several ways: all geometry
// is wrapped in a single inner <svg> with a huge viewBox; axes/ticks/labels are
// *colored* to match their data (so "achromatic = structure" misfires and the
// blue Y-axis is read as a data series); gray (#808080) is used as a real data
// color (so the achromatic rule drops that whole series to "decoration"); markers
// are drawn as <polygon>/<rect>; and every element carries a class / olab:scope
// taxonomy (Layer/Axis/SubAxis/Tick/TickLabel/Title/Plot) that is ground truth.
// We normalize the document into one coordinate space and classify straight from
// that taxonomy, bypassing the color heuristic entirely.
// ---------------------------------------------------------------------------
const OLAB_NS = "http://www.originlab.com/namespaces/olab";

function isOriginSvg(raw: string): boolean {
  return /originlab|Generated by Origin/i.test(raw);
}

/** class + olab:scope of a node, lowercased — the Origin role/grouping taxonomy. */
function originHint(node: Element): string {
  const cls = node.getAttribute("class") || "";
  const scope = node.getAttribute("olab:scope") || node.getAttributeNS(OLAB_NS, "scope") || "";
  return `${cls} ${scope}`.toLowerCase();
}

/**
 * Role from Origin's object-model taxonomy (carried in class / olab:scope). The
 * scope is a path through Origin's documented graph object model —
 * `Layer.Axis.SubAxis.<part>` for structure, `Layer.Plot<n>` / `…Bar` / `…Symbol`
 * for data, plus `Legend`, `ColorScale`, `ErrorBar`, etc. The object-type tokens
 * are shared across chart types, so keying off them classifies a bar / scatter /
 * legend / error-bar graph by the same rules as a line plot. Returns null only when
 * there's no usable scope (let the generic classifier decide).
 */
function originRoleFromHint(node: Element, tag: string, bbox: BBox, vb: BBox): ElementRole | null {
  const s = originHint(node);
  if (!s.trim()) return null;
  // an inserted bitmap (micrograph, logo) -> let the generic/bitmap path handle it
  // (it may flip the panel to layout-only); never fold it into the legend bucket.
  if (tag === "image") return null;
  const isText = tag === "text";
  const has = (re: RegExp) => re.test(s);
  // a scatter symbol is small in BOTH dimensions; a bar/column is small in only one
  // (its width) but spans its value in the other — so require both to be small.
  const vbMax = Math.max(vb.w, vb.h);
  const small = bbox.w < vbMax * 0.06 && bbox.h < vbMax * 0.06;
  const markerTag = /^(polygon|rect|circle|ellipse|use|path)$/.test(tag);

  // ---- axis structure (most specific first; "ticklabel" contains "tick") --------
  if (has(/tick-?labels?/)) return "text-tick"; // numeric OR category tick labels
  if (has(/\btick\b|(?:major|minor)-?ticks?|ticks?-?(?:major|minor)/)) return isText ? "text-tick" : "tick";
  if (has(/\btitle\b/)) return isText ? "text-axis" : null; // axis / plot title
  if (has(/\bgrid\b/)) return "grid"; // grid lines
  if (has(/legend/)) return isText ? "text-legend" : "legend"; // legend text / swatch
  if (has(/colou?r-?scale|colou?r-?bar|\bzscale\b|bubble-?scale/)) return isText ? "text-tick" : "decoration";
  if (has(/\bbreak\b|axis-?break/)) return "axis"; // axis-break marks
  if (has(/\barrow\b/) && has(/axis/)) return "axis";

  // ---- data objects (Plot / Bar / Column / Area / Symbol / ErrorBar / …) --------
  if (has(/error|whisker|\bcap\b/)) return "errorbar";
  if (has(/reference|\bhline\b|\bvline\b/)) return "auxiliary";
  if (has(/data-?labels?/)) return isText ? "text-legend" : "decoration";
  if (has(/\bplot\d*\b|\.plot|\bbars?\b|\bcolumns?\b|\barea\b|histogram|\bpie\b|\bbox\b|symbol|scatter|\bcurve\b|\bfit\b|series/)) {
    if (isText) return "text-legend"; // data / point label sitting in the plot
    if (has(/\bfit\b/)) return "fit";
    if (has(/symbol|scatter/) || (markerTag && small)) return "scatter";
    return "data";
  }

  // ---- axis line (checked AFTER Plot so a data 'line' isn't grabbed) ------------
  if (has(/\bline\b|spine|frame|border/) && has(/axis/)) return isText ? "text-axis" : "axis";

  // ---- fallback ----------------------------------------------------------------
  // Anything still under an axis (but not Title/Tick/Line) is a tick/axis label —
  // covers category names if a future export tags them oddly.
  if (has(/axis/)) return isText ? "text-tick" : "axis";
  // Everything else with a scope is a LAYER-LEVEL object. In real Origin SVG the
  // legend is scoped bare "Layer{N}" (box polylines + colored swatch polygons +
  // entry text), as are free annotations. Treat it as legend so the colored
  // swatches never inflate the data-series count and instead recolor with their
  // series (pairLegends matches role "legend"/"text-legend" by color/proximity).
  return isText ? "text-legend" : "legend";
}

/**
 * liborigin-informed refinement. In Origin's SVG the legend, free-text annotations,
 * arrows and drawn shapes ALL sit under a bare `Layer{N}` scope, so originRoleFromHint
 * can only provisionally call every non-text bare-Layer shape a legend swatch. But a
 * REAL legend swatch's fill/stroke is byte-identical to a data series (see ORIGIN-SVG.md);
 * a decorative arrow / box / line is not. Once series are aggregated we can tell them
 * apart: a "legend" element whose color matches no series is a decoration — leave it
 * alone (don't recolor it or count it as legend), not a swatch. Mirrors liborigin's clean
 * split of Legend vs Line/Figure annotations, but stays rule-based off the received SVG.
 * Conservative: real swatches (color == series) are untouched; pure model edit, caller
 * rewrites data-scrole after.
 */
function refineOriginLegendRoles(elements: ParsedElement[], series: DataSeries[]): void {
  if (!series.length) return;
  const seriesColors = new Set(series.map((s) => s.color));
  for (const e of elements) {
    if (e.role !== "legend") continue;
    const c = parseColor(seriesColorOf(e));
    const hex = c ? toHex(c) : null;
    if (!hex || !seriesColors.has(hex)) e.role = "decoration";
  }
}

/**
 * Normalize an Origin export into a flat, single-coordinate-space SVG so the bake
 * / figsize / recolor pipeline (which assumes one coordinate system, like a
 * matplotlib export) works:
 *  1. flatten the nested <svg> wrapper — adopt its viewBox and hoist its children
 *     to the root, so geometry, vb and the plot box all share one space;
 *  2. drop the plot-area clip mask — after the import bake scales geometry, an
 *     un-scaled mask would hide everything (Origin already clipped to range);
 *  3. convert rotated axis titles from transform="matrix(...)" to x/y + rotate()
 *     and strip <tspan> x/y, so glyph anchors live on the (scalable) <text> the
 *     bake / figsize step understands.
 */
function normalizeOriginSvg(svg: SVGSVGElement): void {
  for (let guard = 0; guard < 4; guard++) {
    const inner = Array.from(svg.children).find((c) => c.tagName.toLowerCase() === "svg");
    if (!inner) break;
    const innerVB =
      inner.getAttribute("viewBox") ||
      `0 0 ${inner.getAttribute("width") || 0} ${inner.getAttribute("height") || 0}`;
    svg.setAttribute("viewBox", innerVB);
    while (inner.firstChild) svg.insertBefore(inner.firstChild, inner);
    inner.remove();
  }

  // Pin width/height to the viewBox so geometry measures 1:1 (getBBox·getCTM scales
  // by width/viewBox; Origin's root width/height are in inches, ~6x off — true for
  // BOTH nested and non-nested exports). The final panel size is set by the bake;
  // this is only for measurement and the per-layer viewBoxes of multi-layer splits.
  const vbAttr = svg.getAttribute("viewBox");
  if (vbAttr) {
    const [, , vw, vh] = vbAttr.split(/[\s,]+/).map(Number);
    if (Number.isFinite(vw) && Number.isFinite(vh) && vw > 0 && vh > 0) {
      svg.setAttribute("width", String(vw));
      svg.setAttribute("height", String(vh));
    }
  }

  svg.querySelectorAll("[mask]").forEach((el) => el.removeAttribute("mask"));
  svg.querySelectorAll("[clip-path]").forEach((el) => el.removeAttribute("clip-path"));
  svg.querySelectorAll("mask,clipPath").forEach((el) => el.remove());

  svg.querySelectorAll("text").forEach((t) => {
    const tf = t.getAttribute("transform");
    const m = tf ? tf.match(/matrix\(([^)]+)\)/) : null;
    if (m) {
      const n = m[1].split(/[\s,]+/).map(Number);
      if (n.length === 6 && n.every((v) => Number.isFinite(v))) {
        const [a, b, , , e, f] = n;
        const deg = Math.round((Math.atan2(b, a) * 180) / Math.PI);
        t.setAttribute("x", String(e));
        t.setAttribute("y", String(f));
        if (deg) t.setAttribute("transform", `rotate(${deg} ${e} ${f})`);
        else t.removeAttribute("transform");
      }
    }
    // Strip tspan x/y so each glyph flows from the (scalable, transform-positioned)
    // text anchor. Origin sets tspan x to either the text x (tick labels) or 0
    // (rotated titles, positioned via the matrix) — both must be dropped. The merged
    // multi-part title uses natural flow + baseline-shift, so it has no tspan x/y.
    t.querySelectorAll("tspan").forEach((sp) => {
      sp.removeAttribute("x");
      sp.removeAttribute("y");
    });
  });
}

/** rect-as-bbox in the svg root user space (handles ancestor transforms). */
function rootBBox(el: SVGGraphicsElement): BBox {
  let b: DOMRect;
  try {
    b = el.getBBox();
  } catch {
    return { x: 0, y: 0, w: 0, h: 0 };
  }
  const ctm = el.getCTM();
  if (!ctm) return { x: b.x, y: b.y, w: b.width, h: b.height };
  const corners = [
    [b.x, b.y],
    [b.x + b.width, b.y],
    [b.x, b.y + b.height],
    [b.x + b.width, b.y + b.height]
  ].map(([x, y]) => ({ x: ctm.a * x + ctm.c * y + ctm.e, y: ctm.b * x + ctm.d * y + ctm.f }));
  const xs = corners.map((c) => c.x);
  const ys = corners.map((c) => c.y);
  const minx = Math.min(...xs);
  const miny = Math.min(...ys);
  return { x: minx, y: miny, w: Math.max(...xs) - minx, h: Math.max(...ys) - miny };
}

function isMarkerLike(el: Element): boolean {
  const tag = el.tagName.toLowerCase();
  if (el.hasAttribute("data-scshape")) return true; // reshaped scatter marker
  if (el.getAttribute("data-scrole") === "scatter") return true; // recognized scatter (e.g. Origin polygon/rect)
  if (tag === "use") return true;
  if (tag === "circle" || tag === "ellipse") return true;
  // a small filled path inside a marker/scatter group
  if (tag === "path" && /marker|scatter|collection/i.test(idHintOf(el))) return true;
  return false;
}

/** Ensure the svg has xmlns + a viewBox so it renders predictably. */
function ensureRenderable(svg: SVGSVGElement): BBox {
  if (!svg.getAttribute("xmlns")) svg.setAttribute("xmlns", SVGNS);
  // figsize: stretch content to fill the box (axis lengths follow the box);
  // figsize compensation keeps text + stroke widths fixed (see mutate.applyFigsize).
  svg.setAttribute("preserveAspectRatio", "none");
  const vbAttr = svg.getAttribute("viewBox");
  if (vbAttr) {
    const [x, y, w, h] = vbAttr.split(/[\s,]+/).map(Number);
    if ([x, y, w, h].every((n) => Number.isFinite(n)) && w > 0 && h > 0) return { x, y, w, h };
  }
  const w = parseFloat(svg.getAttribute("width") || "");
  const h = parseFloat(svg.getAttribute("height") || "");
  if (Number.isFinite(w) && Number.isFinite(h) && w > 0 && h > 0) {
    svg.setAttribute("viewBox", `0 0 ${w} ${h}`);
    return { x: 0, y: 0, w, h };
  }
  return { x: 0, y: 0, w: 100, h: 100 };
}

/** The color that identifies an element's data series. A colored fill marks a
 * filled shape (bar / area / scatter marker) and wins; an unfilled line is
 * identified by its stroke. */
function seriesColorOf(el: ParsedElement): string | null {
  const fillData = classifyColor(el.fill) === "data";
  const strokeData = classifyColor(el.stroke) === "data";
  if (fillData) return el.fill;
  if (strokeData) return el.stroke;
  return el.stroke ?? el.fill;
}

/** Normalized hex key for grouping by color (C3 fallback). */
function colorKey(el: ParsedElement): string {
  const rgb = parseColor(seriesColorOf(el));
  return rgb ? toHex(rgb) : "none";
}

/** Group key for series aggregation: prefer a meaningful ancestor id. */
function groupKeyOf(node: Element, el: ParsedElement): string {
  // Origin: group by Layer + data-object (Plot/Bar/Column/Area) so each dataset is
  // its own series regardless of color (two same-colored datasets must not merge;
  // a line and its markers must).
  const oh = originHint(node);
  const layer = oh.match(/layer(\d+)/);
  const plot = oh.match(/(?:plot|bars?|columns?|area)(\d+)/);
  if (layer && plot) return `g:origin:l${layer[1]}p${plot[1]}`;

  let p: Element | null = node;
  let depth = 0;
  while (p && depth < 6) {
    const id = p.getAttribute("id") || "";
    if (/(line2d|pathcollection|errorbar|lines?_?\d|collection|series|patch|fill_|poly)/i.test(id)) {
      return `g:${id}`;
    }
    p = p.parentElement;
    depth += 1;
  }
  // direct parent group with any id
  const parentId = node.parentElement?.getAttribute("id");
  if (parentId) return `g:${parentId}`;
  return `c:${colorKey(el)}`;
}

/**
 * Parse a raw SVG string. Must run in the browser (uses getBBox).
 */
export function parseSvgString(raw: string, sourceName = "figure"): ParseResult {
  const warnings: ImportWarning[] = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(raw, "image/svg+xml");
  const perr = doc.querySelector("parsererror");
  const svg = doc.documentElement as unknown as SVGSVGElement;
  if (perr || !svg || svg.tagName.toLowerCase() !== "svg") {
    warnings.push({ kind: "parse", message: "This file could not be parsed as SVG." });
    return { svg: raw, vb: { x: 0, y: 0, w: 100, h: 100 }, elements: [], series: [], textToPath: false, mode: "layout-only", warnings };
  }

  // Origin exports need flattening + clip/title fixes before geometry is measured.
  const origin = isOriginSvg(raw);
  if (origin) normalizeOriginSvg(svg);

  const vb = ensureRenderable(svg);

  // Import into the live document so geometry can be measured.
  const mount = document.createElement("div");
  mount.setAttribute("style", "position:fixed;left:-99999px;top:-99999px;width:10px;height:10px;overflow:hidden;opacity:0;pointer-events:none;");
  const liveSvg = document.importNode(svg, true) as SVGSVGElement;
  mount.appendChild(liveSvg);
  document.body.appendChild(mount);

  const elements: ParsedElement[] = [];
  const nodeByScid = new Map<string, Element>();

  try {
    const all = Array.from(liveSvg.querySelectorAll("*"));
    let textCount = 0;
    let glyphPathCount = 0;
    let imageArea = 0;

    for (const node of all) {
      const tag = node.tagName.toLowerCase();
      if (tag === "text") textCount += 1;
      if (!DRAWABLE.has(tag)) continue;
      if (inSkippedAncestor(node)) continue;

      const stroke = getStyleValue(node, "stroke");
      const fill = getStyleValue(node, "fill");
      const bbox = rootBBox(node as unknown as SVGGraphicsElement);

      // text-as-path signal: small filled achromatic paths (glyph outlines)
      if (tag === "path") {
        const small = Math.max(bbox.w, bbox.h) < Math.max(vb.w, vb.h) * 0.05;
        const filledDark = classifyColor(fill) === "black" || classifyColor(fill) === "gray";
        if (small && filledDark) glyphPathCount += 1;
      }
      if (tag === "image") imageArea += Math.max(0, bbox.w) * Math.max(0, bbox.h);

      let scid = node.getAttribute("data-scid");
      if (!scid) {
        scid = nextScid();
        node.setAttribute("data-scid", scid);
      }
      nodeByScid.set(scid, node);

      let length = Math.max(bbox.w, bbox.h);
      const geom = node as unknown as SVGGeometryElement;
      if (typeof geom.getTotalLength === "function") {
        try {
          const l = geom.getTotalLength();
          if (Number.isFinite(l) && l > 0) length = l;
        } catch {
          /* keep bbox-derived length */
        }
      }

      const fontSize = tag === "text" ? getStyleNumber(node, "font-size") : null;

      const el: ParsedElement = {
        scid,
        tag,
        role: (node.getAttribute("data-scrole") as ElementRole) || "unknown",
        idHint: idHintOf(node),
        groupKey: "",
        seriesId: node.getAttribute("data-scseries"),
        stroke: stroke ?? null,
        fill: fill ?? null,
        fillOpacity: getStyleNumber(node, "fill-opacity"),
        opacity: getStyleNumber(node, "opacity"),
        strokeWidth: getStyleNumber(node, "stroke-width"),
        strokeDasharray: getStyleValue(node, "stroke-dasharray"),
        gradientId: resolveGradientId(fill),
        bbox,
        pathLength: length,
        isGray: ["black", "white", "gray"].includes(classifyColor(stroke) ?? classifyColor(fill) ?? ""),
        hasMarker: isMarkerLike(node),
        text: tag === "text" ? node.textContent : null,
        fontSizePx: fontSize,
        hidden: getStyleValue(node, "display") === "none",
        rotated: /rotate/i.test(node.getAttribute("transform") ?? "")
      };
      el.groupKey = groupKeyOf(node, el);
      // Origin: classify from the class/olab:scope taxonomy (ground truth) instead
      // of color, so colored axes and gray data series land in the right role. Only
      // for freshly-imported elements (role still unknown) — user/prior overrides win.
      if (origin && el.role === "unknown") {
        const r = originRoleFromHint(node, tag, bbox, vb);
        if (r) {
          el.role = r;
          if (r === "scatter") el.hasMarker = true;
        }
      }
      elements.push(el);
    }

    // ---- C2: text converted to paths -----------------------------------
    const textToPath = textCount === 0 && glyphPathCount >= 10;
    if (textToPath) {
      warnings.push({
        kind: "text-as-path",
        message:
          "Text in this SVG was converted to paths — fonts can't be edited. Re-export keeping text (e.g. matplotlib svg.fonttype='none')."
      });
    }

    // ---- bitmap / layout-only ------------------------------------------
    let mode: PanelMode = "full";
    if (imageArea > 0.5 * vb.w * vb.h) {
      mode = "layout-only";
      warnings.push({
        kind: "bitmap",
        message: "This figure is mostly a bitmap image — layout only (its internal styles can't be edited)."
      });
    }

    // ---- color-scale (heatmap-like) detection --------------------------
    const gradients = Array.from(liveSvg.querySelectorAll("linearGradient,radialGradient"));
    const manyStops = gradients.some((g) => g.querySelectorAll("stop").length > 8);
    const distinctDataFills = new Set(
      elements.filter((e) => classifyColor(e.fill) === "data").map((e) => colorKey(e))
    );
    const looksLikeColorScale = (manyStops || distinctDataFills.size > 12) && textCount < 6;
    if (looksLikeColorScale && mode === "full") {
      warnings.push({
        kind: "color-scale",
        message: "This looks like a continuous color-scale figure (heatmap/contour) — recoloring would change its meaning. Layout only is recommended."
      });
    }

    // ---- Module D1: role recognition -----------------------------------
    assignRoles(elements);
    for (const e of elements) {
      const node = nodeByScid.get(e.scid);
      if (node) node.setAttribute("data-scrole", e.role);
    }

    // ---- C3: aggregate data series -------------------------------------
    const series = aggregateSeries(elements);
    for (const s of series) {
      for (const id of s.elementIds) {
        nodeByScid.get(id)?.setAttribute("data-scseries", s.id);
      }
    }

    // liborigin-informed: a bare-Layer "legend" shape whose color matches no series is a
    // decorative annotation (arrow / box / line), not a swatch — demote it so it isn't
    // recolored or counted as legend. Rewrite data-scrole for any role we changed.
    if (origin) {
      refineOriginLegendRoles(elements, series);
      for (const e of elements) nodeByScid.get(e.scid)?.setAttribute("data-scrole", e.role);
    }

    pairLegends(series, elements);

    const outSvg = new XMLSerializer().serializeToString(liveSvg);
    return { svg: outSvg, vb, elements, series, textToPath, mode, warnings };
  } finally {
    document.body.removeChild(mount);
  }
}

/**
 * If `raw` is a multi-LAYER Origin graph whose layers occupy DISJOINT regions
 * (tiled / stacked panels — NOT an overlaid double-Y like Graph3), split it into one
 * self-contained SVG string per layer (so each becomes its own SciCompose panel,
 * which is exactly the compose-from-sub-figures model). Returns null for a single
 * region or overlaid layers (import as one panel). Browser-only (uses getBBox).
 *
 * Origin encodes layering purely in the `olab:scope` prefix (`Layer{N}.…`), not via
 * DOM containers, so we partition elements by that prefix and crop each panel's
 * viewBox to its layer's bounding box.
 */
export function splitTiledOriginLayers(raw: string): string[] | null {
  if (!isOriginSvg(raw)) return null;
  const doc = new DOMParser().parseFromString(raw, "image/svg+xml");
  const svg = doc.documentElement as unknown as SVGSVGElement;
  if (!svg || svg.tagName.toLowerCase() !== "svg" || doc.querySelector("parsererror")) return null;
  normalizeOriginSvg(svg);
  ensureRenderable(svg);

  const layerOf = (el: Element): number | null => {
    const m = originHint(el).match(/layer(\d+)/);
    return m ? parseInt(m[1], 10) : null;
  };

  const mount = document.createElement("div");
  mount.setAttribute("style", "position:fixed;left:-99999px;top:-99999px;width:10px;height:10px;overflow:hidden;opacity:0;pointer-events:none;");
  const live = document.importNode(svg, true) as SVGSVGElement;
  mount.appendChild(live);
  document.body.appendChild(mount);
  try {
    const boxes = new Map<number, BBox>();
    for (const node of Array.from(live.querySelectorAll("*"))) {
      if (!DRAWABLE.has(node.tagName.toLowerCase()) || inSkippedAncestor(node)) continue;
      const L = layerOf(node);
      if (L == null) continue;
      const b = rootBBox(node as unknown as SVGGraphicsElement);
      if (b.w <= 0 && b.h <= 0) continue;
      const cur = boxes.get(L);
      if (!cur) boxes.set(L, { ...b });
      else {
        const x = Math.min(cur.x, b.x);
        const y = Math.min(cur.y, b.y);
        boxes.set(L, { x, y, w: Math.max(cur.x + cur.w, b.x + b.w) - x, h: Math.max(cur.y + cur.h, b.y + b.h) - y });
      }
    }
    const layers = [...boxes.keys()].sort((a, b) => a - b);
    if (layers.length < 2) return null;
    // tiled ONLY if no two layers meaningfully overlap (an overlaid double-Y shares
    // one plot region and must stay a single panel).
    let maxOverlap = 0;
    for (let i = 0; i < layers.length; i++) {
      for (let j = i + 1; j < layers.length; j++) {
        const a = boxes.get(layers[i])!;
        const b = boxes.get(layers[j])!;
        const ix = Math.max(0, Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x));
        const iy = Math.max(0, Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y));
        maxOverlap = Math.max(maxOverlap, (ix * iy) / Math.max(1, Math.min(a.w * a.h, b.w * b.h)));
      }
    }
    if (maxOverlap > 0.25) return null;

    const out: string[] = [];
    for (const L of layers) {
      const clone = svg.cloneNode(true) as SVGSVGElement;
      for (const node of Array.from(clone.querySelectorAll("*"))) {
        if (!DRAWABLE.has(node.tagName.toLowerCase()) || inSkippedAncestor(node)) continue;
        const m = originHint(node).match(/layer(\d+)/);
        if (!m || parseInt(m[1], 10) !== L) node.remove();
      }
      const bb = boxes.get(L)!;
      const pad = Math.max(2, Math.max(bb.w, bb.h) * 0.02);
      const x = bb.x - pad;
      const y = bb.y - pad;
      const w = bb.w + 2 * pad;
      const h = bb.h + 2 * pad;
      clone.setAttribute("viewBox", `${x} ${y} ${w} ${h}`);
      clone.setAttribute("width", String(w));
      clone.setAttribute("height", String(h));
      clone.setAttribute("preserveAspectRatio", "none");
      out.push(new XMLSerializer().serializeToString(clone));
    }
    return out;
  } finally {
    document.body.removeChild(mount);
  }
}

/** C3 — build DataSeries from data-role elements (pure, model-only). */
export function aggregateSeries(elements: ParsedElement[]): DataSeries[] {
  const groups = new Map<string, ParsedElement[]>();
  for (const e of elements) {
    if (!DATA_ROLES.includes(e.role)) continue;
    // Sub-divide a group by representative color: differently-colored curves
    // that merely share a parent <g> (e.g. Origin exports) must not merge into
    // one series, while same-colored members (a dashed line's segments, a
    // scatter cloud, a bar set) stay together.
    const rgb = parseColor(seriesColorOf(e));
    const ck = rgb ? toHex(rgb) : "none";
    const key = `${e.groupKey}|${ck}`;
    const arr = groups.get(key) ?? [];
    arr.push(e);
    groups.set(key, arr);
  }

  const series: DataSeries[] = [];
  let order = 0;
  for (const [key, members] of groups) {
    // representative color: most frequent data color among members
    // (markers use their fill, lines use their stroke — see seriesColorOf)
    const counts = new Map<string, number>();
    for (const m of members) {
      const rgb = parseColor(seriesColorOf(m));
      if (rgb) {
        const hex = toHex(rgb);
        counts.set(hex, (counts.get(hex) ?? 0) + 1);
      }
    }
    let color = "#888888";
    let best = -1;
    for (const [hex, n] of counts) if (n > best) ((best = n), (color = hex));

    const roleVote = new Map<ElementRole, number>();
    for (const m of members) roleVote.set(m.role, (roleVote.get(m.role) ?? 0) + 1);
    let role: ElementRole = "data";
    let bestRole = -1;
    for (const [r, n] of roleVote) if (n > bestRole) ((bestRole = n), (role = r));

    const isFill = members.some((m) => classifyColor(m.fill) === "data");
    const gradientId = members.find((m) => m.gradientId)?.gradientId ?? null;
    const id = `s${hashKey(key)}`; // stable across re-aggregation (groupKey is stable)
    for (const m of members) m.seriesId = id;
    series.push({
      id,
      role,
      elementIds: members.map((m) => m.scid),
      color,
      emphasis: "normal",
      label: null,
      legendElementId: null,
      hasMarker: members.some((m) => m.hasMarker),
      isFill,
      gradientId,
      order
    });
    order += 1;
  }
  return series;
}

/** D3 — pair each series with a legend text by color proximity. */
function pairLegends(series: DataSeries[], elements: ParsedElement[]): void {
  const legendTexts = elements.filter((e) => e.role === "text-legend");
  // Explicit legend swatches win. A tiny data glyph is only a *fallback* (matplotlib
  // sometimes draws legend keys as small line2d/markers without a legend id). Without
  // this preference a small scatter point (pathLength<40) gets matched as the "swatch",
  // so recoloring hits the data point and the real legend key never changes.
  const explicit = elements.filter((e) => e.role === "legend");
  const fallback = elements.filter((e) => DATA_ROLES.includes(e.role) && e.pathLength < 40);
  const usedTexts = new Set<string>();
  for (const s of series) {
    const match = (sw: ParsedElement) => {
      const c = parseColor(seriesColorOf(sw));
      return !!c && toHex(c) === s.color;
    };
    // find a swatch whose color matches this series — explicit legend keys first
    const swatch = explicit.find(match) ?? fallback.find(match);
    if (!swatch) continue;
    // nearest legend text by *vertical center* (text bbox.y is the top, so
    // comparing tops to the swatch line would bias toward the row below)
    const swCy = swatch.bbox.y + swatch.bbox.h / 2;
    let nearestText: ParsedElement | null = null;
    let nd = Infinity;
    for (const t of legendTexts) {
      if (usedTexts.has(t.scid)) continue;
      const tCy = t.bbox.y + t.bbox.h / 2;
      const dx = t.bbox.x - (swatch.bbox.x + swatch.bbox.w);
      const dy = tCy - swCy;
      const d = Math.abs(dy) + Math.max(0, dx);
      if (d < nd) ((nd = d), (nearestText = t));
    }
    if (nearestText) {
      usedTexts.add(nearestText.scid);
      s.label = (nearestText.text ?? "").trim() || null;
      s.legendElementId = swatch.scid;
    }
  }
}

export { scidCounter };
